### ISSUE TITLE
had issue when running the cli

### ISSUE THREAD

**Issue by stanosaka** [DominicRoyStang/uvindex#119]
`./uvindex-cli                                                                                                                                                                     [14:11:21]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }', src/main.rs:53:75
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by DominicRoyStang** [comment]
Thanks for reporting this! I'll look into it this week

**Comment by DominicRoyStang** [comment]
I'm no longer seeing this issue when I run `uvindex`. I'll still try to add better handling of API responses so we get a nicer error message in the future should this error show up again.
